---
title: "Tutorial Jail, Learning, and Tidymodels"
description: |
  Avoid tutorial jail with this resource to get you started in tidymodels.
base_url: https://jarrodpelkofer.netlify.app/
author:
  - name: Jarrod Pelkofer
    url:
    affiliation:
    affiliation_url: 
date: 05-13-2020
output: 
  distill::distill_article:
    self_contained: false
twitter:
  creator: "@jpelk33"
---

```{r setup, layout="1-body-outset", include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Tutorial jail!

Sound familiar?

Many have wasted days, months, and even years in this jail. The tricky part, this jail is deceiving. When wasting away in this jail you think you are being productive.

This can make it hard to realize when you have been put in tutorial jail. In the past month, if you have read through an online tutorial, ask yourself these questions:

*	Do you remember what the tutorial was about?
*	Did you follow along step by step with the tutorial?
*	Have you used anything from the tutorial in your own work?
*	Have you revisited any topics you “learned” from the tutorial?

If you answered no to any of these questions, chances are you have spent some time in tutorial jail.

I have spent a fair amount of time in tutorial jail. More than I care to admit.

Let me paint my picture for you.

Step 1: Something catches my eye on Twitter. I start to get those warm fuzzy feelings. I know this is what I need to take me over the top. (The top of what? Who knows?)

Step 2: I click the link (or perhaps favorite it, telling myself I will check it out later…). Fuzzy feelings increase.

Step 3: I read through the tutorial, maybe I even follow along step by step typing out every line of code provided. The endorphins are really running through my brain now. Watch out!

Step 4: I have just completed the entire tutorial. I have got skills that put me on another level and ideas that are going to change the world!

Step 5: A month has passed. The tutorial has not crossed my mind since they day I read it. Fuzzy feelings have disintegrated. 

Hopefully, this picture is not as familiar to you as it is to me. 

# Flashcards and Spaced Repitition

“Work on your own projects”. Yes, we hear this all the time. The best way to learn is to work on your own projects. Come up with ideas and try to implement them.

I don’t disagree with this at all. I have learned a ton from working on projects.

But let’s be honest, projects take time. I have a family, full time job, and am closing out a master’s degree. I do not have time to build out a project for every cool tutorial that I work through. No one does. 

This is where the idea of flashcards and spaced repetition can be a beneficial learning resource. We all are familiar with flashcards but some of us may have not heard of spaced repetition. An example might be the best way to help understand the concept. On day 1 I am shown a flashcard. I try to answer that flashcard. I will then rate how easy or hard that card was for me to answer. This will inform the software’s algorithm to when I should be shown that card again.

You can find a ton more about spaced repetition by googling it. Luckily, I was introduced to this concept of learning through a course on [Sharp Sight Labs]( https://www.sharpsightlabs.com/). It has really accelerated my ability to learn and retain things that I want to. 

There are a ton of programs online to get started with this learning concept. The two that I have used are: [Anki](https://apps.ankiweb.net/) and [iDoRecall](https://idorecall.com/ ).

As with everything, there are some downsides to spaced repetition. It is something that really should be done every day. The amount of time it takes will depend on the number of cards you have. I typically will spend 15-30 minutes a day reviewing cards. It is easy to fall behind if you do not keep up. Trust me I know from experience.

Spaced repetition should not replace projects. It should act as a supplement to projects. I use it to keep concepts and ideas fresh in my mind. 

# Tidymodels

As an avid R user, the recent launch of the [Tidymodels](https://www.tidymodels.org/) website caught my eye. But with work, family (2nd baby on the way!), and summer school a machine learning project does not seem to be on the horizon for me.

Enter flashcards and spaced repetition!

Over the course of a week, I spent some evenings going through the articles in the [Get Started](https://www.tidymodels.org/start/) section of the tidymodels website. As I worked through the tutorials and learned the concepts, I made flashcards to help remember the syntax and processes that tidymodels uses. It is important to note that I worked through and LEARNED the concepts prior to making the cards.

If you want to check out the cards I made a downloadable Anki deck which can be found [here](https://github.com/jpelkofer/distill_blog/blob/master/_posts/Tidymodels%20Flashcards/tidymodels_basics.apkg). Note: I originally made them on iDoRecall and copied them over as Anki cards because it is free and easy to load.

To benefit from the deck, I recommend going through the [Get Started](https://www.tidymodels.org/start/) posts first then testing your knowledge through the use of the cards. Or just make your own cards, which I find greatly beneficial.

Let’s post some bail and get out of tutorial jail! <- (nice corny jingle to close)


